CREATE TABLE Task (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    course_id BIGINT(20) NOT NULL,
    statement VARCHAR(255) NOT NULL,
    order_index INT NOT NULL,
    type ENUM('OPEN_TEXT', 'MULTIPLE_CHOICE', 'SINGLE_CHOICE')
         CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),

    CONSTRAINT FK_Task_Course
        FOREIGN KEY (course_id)
        REFERENCES Course(id) ON DELETE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
